import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Layout from '../components/Layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Website Pribadi',
  description: 'Website pribadi untuk menampilkan proyek dan esai.',
  openGraph: {
    title: 'Website Pribadi',
    description: 'Website pribadi untuk menampilkan proyek dan esai.',
    url: 'http://localhost:3000/',
    siteName: 'Website Pribadi',
    images: [
      {
        url: 'https://i.pinimg.com/originals/fb/84/f8/fb84f87ea6a881abcd23e24409831df7.gif',
        width: 1200,
        height: 630,
        alt: 'Website Pribadi',
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Website Pribadi',
    description: 'Website pribadi untuk menampilkan proyek dan esai.',
    images: ['https://i.pinimg.com/originals/fb/84/f8/fb84f87ea6a881abcd23e24409831df7.gif'],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}





// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
